# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 85da279b380c1f1a2f658498d2d0fae28fa128cadf3cf665c8bfa61283afe097c936704bf46914aff706d3e135701dbdaadbf6320833a0cbe3df7ce27b098e10

test:
  secret_key_base: 0525108119aba387033820ba9c09e32402a52c24bfe1aafd1c6891ecb40983bc2231968f10f0857e418cd8ad518d8d33bcf749ff2e98d4a34445e660a9b090a6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
